// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shardHeaderExtended.proto

package block

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	transaction "github.com/multiversx/mx-chain-core-go/data/transaction"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ShardHeaderExtended extends the HeaderV2 structure with extra fields needed by sovereign chain
type ShardHeaderExtended struct {
	Header             *HeaderV2            `protobuf:"bytes,1,opt,name=Header,proto3" json:"header"`
	Proof              []byte               `protobuf:"bytes,2,opt,name=Proof,proto3" json:"proof"`
	IncomingMiniBlocks []*MiniBlock         `protobuf:"bytes,3,rep,name=IncomingMiniBlocks,proto3" json:"incomingMiniBlocks,omitempty"`
	IncomingEvents     []*transaction.Event `protobuf:"bytes,4,rep,name=IncomingEvents,proto3" json:"incomingEvents,omitempty"`
}

func (m *ShardHeaderExtended) Reset()      { *m = ShardHeaderExtended{} }
func (*ShardHeaderExtended) ProtoMessage() {}
func (*ShardHeaderExtended) Descriptor() ([]byte, []int) {
	return fileDescriptor_549610f8c128bd02, []int{0}
}
func (m *ShardHeaderExtended) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShardHeaderExtended) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ShardHeaderExtended) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardHeaderExtended.Merge(m, src)
}
func (m *ShardHeaderExtended) XXX_Size() int {
	return m.Size()
}
func (m *ShardHeaderExtended) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardHeaderExtended.DiscardUnknown(m)
}

var xxx_messageInfo_ShardHeaderExtended proto.InternalMessageInfo

func (m *ShardHeaderExtended) GetHeader() *HeaderV2 {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ShardHeaderExtended) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *ShardHeaderExtended) GetIncomingMiniBlocks() []*MiniBlock {
	if m != nil {
		return m.IncomingMiniBlocks
	}
	return nil
}

func (m *ShardHeaderExtended) GetIncomingEvents() []*transaction.Event {
	if m != nil {
		return m.IncomingEvents
	}
	return nil
}

func init() {
	proto.RegisterType((*ShardHeaderExtended)(nil), "proto.ShardHeaderExtended")
}

func init() { proto.RegisterFile("shardHeaderExtended.proto", fileDescriptor_549610f8c128bd02) }

var fileDescriptor_549610f8c128bd02 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3d, 0x6e, 0xe2, 0x40,
	0x18, 0x86, 0x3d, 0xb0, 0x20, 0xad, 0x61, 0x7f, 0xe4, 0x6d, 0xbc, 0x08, 0x8d, 0xad, 0xad, 0x28,
	0xd6, 0x58, 0x32, 0x07, 0x58, 0xad, 0x25, 0xa4, 0xdd, 0x22, 0x52, 0xe4, 0x48, 0x14, 0xe9, 0xfc,
	0x33, 0xd8, 0xa3, 0xe0, 0xf9, 0x90, 0x3d, 0x20, 0xd2, 0xe5, 0x08, 0xb9, 0x43, 0x9a, 0x1c, 0x25,
	0x25, 0x25, 0x95, 0x15, 0x86, 0x26, 0x72, 0xc5, 0x11, 0x22, 0xc6, 0x4e, 0x44, 0x42, 0x2a, 0xfb,
	0x7d, 0xe6, 0xd5, 0xf3, 0xcd, 0xa7, 0x51, 0x7f, 0xe6, 0x89, 0x9f, 0x45, 0xff, 0x88, 0x1f, 0x91,
	0x6c, 0xbc, 0xe2, 0x84, 0x45, 0x24, 0x1a, 0xce, 0x33, 0xe0, 0xa0, 0xb5, 0xe4, 0xa7, 0xd7, 0x09,
	0x66, 0x10, 0x5e, 0x55, 0xac, 0xf7, 0x45, 0x86, 0x89, 0x53, 0x47, 0x2b, 0xa6, 0x3c, 0x59, 0x04,
	0xc3, 0x10, 0x52, 0x3b, 0x86, 0x18, 0x6c, 0x89, 0x83, 0xc5, 0x54, 0x26, 0x19, 0xe4, 0x5f, 0x5d,
	0xff, 0x7b, 0x54, 0x4f, 0x17, 0x33, 0x4e, 0x97, 0x24, 0xcb, 0x57, 0x76, 0xba, 0xb2, 0xc2, 0xc4,
	0xa7, 0xcc, 0x0a, 0x21, 0x23, 0x56, 0x0c, 0x76, 0xe4, 0x73, 0xdf, 0xe6, 0x99, 0xcf, 0x72, 0x3f,
	0xe4, 0x14, 0x98, 0x3d, 0x83, 0xb8, 0x52, 0xfc, 0xba, 0x6b, 0xa8, 0x3f, 0x2e, 0x4e, 0xaf, 0xac,
	0x8d, 0xd4, 0x76, 0x45, 0x74, 0x64, 0xa2, 0x41, 0xc7, 0xf9, 0x56, 0xf5, 0x87, 0x15, 0x9c, 0x38,
	0xae, 0x5a, 0x16, 0x46, 0x3b, 0x91, 0xc9, 0xab, 0xab, 0x9a, 0xa1, 0xb6, 0xce, 0x33, 0x80, 0xa9,
	0xde, 0x30, 0xd1, 0xa0, 0xeb, 0x7e, 0x2e, 0x0b, 0xe3, 0xb0, 0x34, 0x4c, 0xbd, 0x8a, 0x6b, 0x81,
	0xaa, 0xfd, 0x67, 0x21, 0xa4, 0x94, 0xc5, 0x67, 0x94, 0x51, 0xf7, 0xb0, 0x7c, 0xae, 0x37, 0xcd,
	0xe6, 0xa0, 0xe3, 0x7c, 0xaf, 0x27, 0xbc, 0x1e, 0xb8, 0x66, 0x59, 0x18, 0x7d, 0x7a, 0xd2, 0xff,
	0x0d, 0x29, 0xe5, 0x24, 0x9d, 0xf3, 0x6b, 0xef, 0x03, 0x9b, 0xe6, 0xa9, 0x5f, 0x5f, 0xe8, 0x78,
	0x49, 0x18, 0xcf, 0xf5, 0x4f, 0xd2, 0xdf, 0xad, 0xfd, 0x12, 0xba, 0xfd, 0xb2, 0x30, 0x74, 0xfa,
	0xa6, 0x77, 0xe4, 0x7d, 0x67, 0x70, 0xff, 0xac, 0xb7, 0x58, 0xd9, 0x6c, 0xb1, 0xb2, 0xdf, 0x62,
	0x74, 0x23, 0x30, 0xba, 0x17, 0x18, 0x3d, 0x08, 0x8c, 0xd6, 0x02, 0xa3, 0x8d, 0xc0, 0xe8, 0x51,
	0x60, 0xf4, 0x24, 0xb0, 0xb2, 0x17, 0x18, 0xdd, 0xee, 0xb0, 0xb2, 0xde, 0x61, 0x65, 0xb3, 0xc3,
	0xca, 0x65, 0x4b, 0x3e, 0x70, 0xd0, 0x96, 0xb3, 0x47, 0xcf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x57,
	0xb4, 0x60, 0x4f, 0x1f, 0x02, 0x00, 0x00,
}

func (this *ShardHeaderExtended) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ShardHeaderExtended)
	if !ok {
		that2, ok := that.(ShardHeaderExtended)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Header.Equal(that1.Header) {
		return false
	}
	if !bytes.Equal(this.Proof, that1.Proof) {
		return false
	}
	if len(this.IncomingMiniBlocks) != len(that1.IncomingMiniBlocks) {
		return false
	}
	for i := range this.IncomingMiniBlocks {
		if !this.IncomingMiniBlocks[i].Equal(that1.IncomingMiniBlocks[i]) {
			return false
		}
	}
	if len(this.IncomingEvents) != len(that1.IncomingEvents) {
		return false
	}
	for i := range this.IncomingEvents {
		if !this.IncomingEvents[i].Equal(that1.IncomingEvents[i]) {
			return false
		}
	}
	return true
}
func (this *ShardHeaderExtended) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&block.ShardHeaderExtended{")
	if this.Header != nil {
		s = append(s, "Header: "+fmt.Sprintf("%#v", this.Header)+",\n")
	}
	s = append(s, "Proof: "+fmt.Sprintf("%#v", this.Proof)+",\n")
	if this.IncomingMiniBlocks != nil {
		s = append(s, "IncomingMiniBlocks: "+fmt.Sprintf("%#v", this.IncomingMiniBlocks)+",\n")
	}
	if this.IncomingEvents != nil {
		s = append(s, "IncomingEvents: "+fmt.Sprintf("%#v", this.IncomingEvents)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringShardHeaderExtended(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *ShardHeaderExtended) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShardHeaderExtended) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ShardHeaderExtended) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IncomingEvents) > 0 {
		for iNdEx := len(m.IncomingEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.IncomingEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintShardHeaderExtended(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.IncomingMiniBlocks) > 0 {
		for iNdEx := len(m.IncomingMiniBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.IncomingMiniBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintShardHeaderExtended(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintShardHeaderExtended(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x12
	}
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintShardHeaderExtended(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintShardHeaderExtended(dAtA []byte, offset int, v uint64) int {
	offset -= sovShardHeaderExtended(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ShardHeaderExtended) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovShardHeaderExtended(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovShardHeaderExtended(uint64(l))
	}
	if len(m.IncomingMiniBlocks) > 0 {
		for _, e := range m.IncomingMiniBlocks {
			l = e.Size()
			n += 1 + l + sovShardHeaderExtended(uint64(l))
		}
	}
	if len(m.IncomingEvents) > 0 {
		for _, e := range m.IncomingEvents {
			l = e.Size()
			n += 1 + l + sovShardHeaderExtended(uint64(l))
		}
	}
	return n
}

func sovShardHeaderExtended(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozShardHeaderExtended(x uint64) (n int) {
	return sovShardHeaderExtended(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ShardHeaderExtended) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForIncomingMiniBlocks := "[]*MiniBlock{"
	for _, f := range this.IncomingMiniBlocks {
		repeatedStringForIncomingMiniBlocks += strings.Replace(fmt.Sprintf("%v", f), "MiniBlock", "MiniBlock", 1) + ","
	}
	repeatedStringForIncomingMiniBlocks += "}"
	repeatedStringForIncomingEvents := "[]*Event{"
	for _, f := range this.IncomingEvents {
		repeatedStringForIncomingEvents += strings.Replace(fmt.Sprintf("%v", f), "Event", "transaction.Event", 1) + ","
	}
	repeatedStringForIncomingEvents += "}"
	s := strings.Join([]string{`&ShardHeaderExtended{`,
		`Header:` + strings.Replace(fmt.Sprintf("%v", this.Header), "HeaderV2", "HeaderV2", 1) + `,`,
		`Proof:` + fmt.Sprintf("%v", this.Proof) + `,`,
		`IncomingMiniBlocks:` + repeatedStringForIncomingMiniBlocks + `,`,
		`IncomingEvents:` + repeatedStringForIncomingEvents + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringShardHeaderExtended(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ShardHeaderExtended) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShardHeaderExtended
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShardHeaderExtended: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShardHeaderExtended: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShardHeaderExtended
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &HeaderV2{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShardHeaderExtended
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncomingMiniBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShardHeaderExtended
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IncomingMiniBlocks = append(m.IncomingMiniBlocks, &MiniBlock{})
			if err := m.IncomingMiniBlocks[len(m.IncomingMiniBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncomingEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShardHeaderExtended
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IncomingEvents = append(m.IncomingEvents, &transaction.Event{})
			if err := m.IncomingEvents[len(m.IncomingEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShardHeaderExtended(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShardHeaderExtended
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipShardHeaderExtended(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowShardHeaderExtended
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShardHeaderExtended
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShardHeaderExtended
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthShardHeaderExtended
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupShardHeaderExtended
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthShardHeaderExtended
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthShardHeaderExtended        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowShardHeaderExtended          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupShardHeaderExtended = fmt.Errorf("proto: unexpected end of group")
)
