// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sovereignChainHeader.proto

package block

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_multiversx_mx_chain_core_go_data "github.com/multiversx/mx-chain-core-go/data"
	io "io"
	math "math"
	math_big "math/big"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OutGoingOpType int32

const (
	OutGoingOpDeposit            OutGoingOpType = 0
	OutGoingOpChangeValidatorSet OutGoingOpType = 30
	OutGoingOpRegisterToken      OutGoingOpType = 60
	OutGoingOpRegisterBlsKey     OutGoingOpType = 90
	OutGoingOpUnRegisterBlsKey   OutGoingOpType = 120
)

var OutGoingOpType_name = map[int32]string{
	0:   "OutGoingOpDeposit",
	30:  "OutGoingOpChangeValidatorSet",
	60:  "OutGoingOpRegisterToken",
	90:  "OutGoingOpRegisterBlsKey",
	120: "OutGoingOpUnRegisterBlsKey",
}

var OutGoingOpType_value = map[string]int32{
	"OutGoingOpDeposit":            0,
	"OutGoingOpChangeValidatorSet": 30,
	"OutGoingOpRegisterToken":      60,
	"OutGoingOpRegisterBlsKey":     90,
	"OutGoingOpUnRegisterBlsKey":   120,
}

func (OutGoingOpType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b9b8ff297a820152, []int{0}
}

// EpochStart holds the block information for end-of-epoch
type EpochStartSovereign struct {
	Economics                     Economics                `protobuf:"bytes,1,opt,name=Economics,proto3" json:"economics"`
	LastFinalizedCrossChainHeader EpochStartCrossChainData `protobuf:"bytes,2,opt,name=LastFinalizedCrossChainHeader,proto3" json:"lastFinalizedCrossChainHeader"`
}

func (m *EpochStartSovereign) Reset()      { *m = EpochStartSovereign{} }
func (*EpochStartSovereign) ProtoMessage() {}
func (*EpochStartSovereign) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9b8ff297a820152, []int{0}
}
func (m *EpochStartSovereign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochStartSovereign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EpochStartSovereign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochStartSovereign.Merge(m, src)
}
func (m *EpochStartSovereign) XXX_Size() int {
	return m.Size()
}
func (m *EpochStartSovereign) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochStartSovereign.DiscardUnknown(m)
}

var xxx_messageInfo_EpochStartSovereign proto.InternalMessageInfo

func (m *EpochStartSovereign) GetEconomics() Economics {
	if m != nil {
		return m.Economics
	}
	return Economics{}
}

func (m *EpochStartSovereign) GetLastFinalizedCrossChainHeader() EpochStartCrossChainData {
	if m != nil {
		return m.LastFinalizedCrossChainHeader
	}
	return EpochStartCrossChainData{}
}

// EpochStartShardData hold the last finalized headers hash and state root hash
type EpochStartCrossChainData struct {
	ShardID    uint32 `protobuf:"varint,1,opt,name=ShardID,proto3" json:"shardID"`
	Epoch      uint32 `protobuf:"varint,9,opt,name=Epoch,proto3" json:"epoch"`
	Round      uint64 `protobuf:"varint,7,opt,name=Round,proto3" json:"round"`
	Nonce      uint64 `protobuf:"varint,8,opt,name=Nonce,proto3" json:"nonce"`
	HeaderHash []byte `protobuf:"bytes,2,opt,name=HeaderHash,proto3" json:"headerHash,omitempty"`
}

func (m *EpochStartCrossChainData) Reset()      { *m = EpochStartCrossChainData{} }
func (*EpochStartCrossChainData) ProtoMessage() {}
func (*EpochStartCrossChainData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9b8ff297a820152, []int{1}
}
func (m *EpochStartCrossChainData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochStartCrossChainData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EpochStartCrossChainData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochStartCrossChainData.Merge(m, src)
}
func (m *EpochStartCrossChainData) XXX_Size() int {
	return m.Size()
}
func (m *EpochStartCrossChainData) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochStartCrossChainData.DiscardUnknown(m)
}

var xxx_messageInfo_EpochStartCrossChainData proto.InternalMessageInfo

func (m *EpochStartCrossChainData) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *EpochStartCrossChainData) GetEpoch() uint32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *EpochStartCrossChainData) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *EpochStartCrossChainData) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *EpochStartCrossChainData) GetHeaderHash() []byte {
	if m != nil {
		return m.HeaderHash
	}
	return nil
}

// SovereignChainHeader extends the Header structure with extra fields needed by sovereign chain
type SovereignChainHeader struct {
	Header                    *Header                    `protobuf:"bytes,1,opt,name=Header,proto3" json:"header"`
	ValidatorStatsRootHash    []byte                     `protobuf:"bytes,2,opt,name=ValidatorStatsRootHash,proto3" json:"validatorStatsRootHash"`
	ExtendedShardHeaderHashes [][]byte                   `protobuf:"bytes,3,rep,name=ExtendedShardHeaderHashes,proto3" json:"extendedShardHeaderHashes,omitempty"`
	OutGoingMiniBlockHeaders  []*OutGoingMiniBlockHeader `protobuf:"bytes,4,rep,name=OutGoingMiniBlockHeaders,proto3" json:"outGoingOperations,omitempty"`
	IsStartOfEpoch            bool                       `protobuf:"varint,5,opt,name=IsStartOfEpoch,proto3" json:"isStartOfEpoch,omitempty"`
	AccumulatedFeesInEpoch    *math_big.Int              `protobuf:"bytes,6,opt,name=AccumulatedFeesInEpoch,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"accumulatedFeesInEpoch,omitempty"`
	DevFeesInEpoch            *math_big.Int              `protobuf:"bytes,7,opt,name=DevFeesInEpoch,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"devFeesInEpoch,omitempty"`
	EpochStart                EpochStartSovereign        `protobuf:"bytes,8,opt,name=EpochStart,proto3" json:"epochStart,omitempty"`
}

func (m *SovereignChainHeader) Reset()      { *m = SovereignChainHeader{} }
func (*SovereignChainHeader) ProtoMessage() {}
func (*SovereignChainHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9b8ff297a820152, []int{2}
}
func (m *SovereignChainHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SovereignChainHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SovereignChainHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SovereignChainHeader.Merge(m, src)
}
func (m *SovereignChainHeader) XXX_Size() int {
	return m.Size()
}
func (m *SovereignChainHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SovereignChainHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SovereignChainHeader proto.InternalMessageInfo

func (m *SovereignChainHeader) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SovereignChainHeader) GetValidatorStatsRootHash() []byte {
	if m != nil {
		return m.ValidatorStatsRootHash
	}
	return nil
}

func (m *SovereignChainHeader) GetExtendedShardHeaderHashes() [][]byte {
	if m != nil {
		return m.ExtendedShardHeaderHashes
	}
	return nil
}

func (m *SovereignChainHeader) GetOutGoingMiniBlockHeaders() []*OutGoingMiniBlockHeader {
	if m != nil {
		return m.OutGoingMiniBlockHeaders
	}
	return nil
}

func (m *SovereignChainHeader) GetIsStartOfEpoch() bool {
	if m != nil {
		return m.IsStartOfEpoch
	}
	return false
}

func (m *SovereignChainHeader) GetAccumulatedFeesInEpoch() *math_big.Int {
	if m != nil {
		return m.AccumulatedFeesInEpoch
	}
	return nil
}

func (m *SovereignChainHeader) GetDevFeesInEpoch() *math_big.Int {
	if m != nil {
		return m.DevFeesInEpoch
	}
	return nil
}

func (m *SovereignChainHeader) GetEpochStart() EpochStartSovereign {
	if m != nil {
		return m.EpochStart
	}
	return EpochStartSovereign{}
}

type OutGoingMiniBlockHeader struct {
	Hash                                  []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"hash,omitempty"`
	OutGoingOperationsHash                []byte `protobuf:"bytes,2,opt,name=OutGoingOperationsHash,proto3" json:"outGoingOperationsHash,omitempty"`
	AggregatedSignatureOutGoingOperations []byte `protobuf:"bytes,3,opt,name=AggregatedSignatureOutGoingOperations,proto3" json:"aggregatedSignatureOutGoingOperations,omitempty"`
	LeaderSignatureOutGoingOperations     []byte `protobuf:"bytes,4,opt,name=LeaderSignatureOutGoingOperations,proto3" json:"leaderSignatureOutGoingOperations,omitempty"`
}

func (m *OutGoingMiniBlockHeader) Reset()      { *m = OutGoingMiniBlockHeader{} }
func (*OutGoingMiniBlockHeader) ProtoMessage() {}
func (*OutGoingMiniBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9b8ff297a820152, []int{3}
}
func (m *OutGoingMiniBlockHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OutGoingMiniBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *OutGoingMiniBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutGoingMiniBlockHeader.Merge(m, src)
}
func (m *OutGoingMiniBlockHeader) XXX_Size() int {
	return m.Size()
}
func (m *OutGoingMiniBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_OutGoingMiniBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_OutGoingMiniBlockHeader proto.InternalMessageInfo

func (m *OutGoingMiniBlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *OutGoingMiniBlockHeader) GetOutGoingOperationsHash() []byte {
	if m != nil {
		return m.OutGoingOperationsHash
	}
	return nil
}

func (m *OutGoingMiniBlockHeader) GetAggregatedSignatureOutGoingOperations() []byte {
	if m != nil {
		return m.AggregatedSignatureOutGoingOperations
	}
	return nil
}

func (m *OutGoingMiniBlockHeader) GetLeaderSignatureOutGoingOperations() []byte {
	if m != nil {
		return m.LeaderSignatureOutGoingOperations
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.OutGoingOpType", OutGoingOpType_name, OutGoingOpType_value)
	proto.RegisterType((*EpochStartSovereign)(nil), "proto.EpochStartSovereign")
	proto.RegisterType((*EpochStartCrossChainData)(nil), "proto.EpochStartCrossChainData")
	proto.RegisterType((*SovereignChainHeader)(nil), "proto.SovereignChainHeader")
	proto.RegisterType((*OutGoingMiniBlockHeader)(nil), "proto.OutGoingMiniBlockHeader")
}

func init() { proto.RegisterFile("sovereignChainHeader.proto", fileDescriptor_b9b8ff297a820152) }

var fileDescriptor_b9b8ff297a820152 = []byte{
	// 905 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xcf, 0x90, 0x26, 0xdd, 0x4e, 0x76, 0x4b, 0x76, 0x58, 0x8a, 0x09, 0x59, 0x3b, 0x14, 0x0a,
	0x11, 0xd0, 0x44, 0x74, 0x2f, 0x48, 0x20, 0xa1, 0xba, 0xe9, 0xb2, 0x11, 0x0b, 0x91, 0x9c, 0x05,
	0xa1, 0x15, 0x97, 0x89, 0xfd, 0xd6, 0x1e, 0x6d, 0x3c, 0x13, 0xd9, 0x93, 0xaa, 0x45, 0x20, 0x71,
	0x45, 0x02, 0x89, 0x0f, 0x01, 0x12, 0xda, 0x4f, 0xb2, 0xc7, 0x1e, 0x2b, 0x0e, 0x86, 0xa6, 0x07,
	0x90, 0x4f, 0xfb, 0x11, 0x90, 0xc7, 0x69, 0xec, 0xfe, 0x71, 0x77, 0x2f, 0x9c, 0x92, 0xf9, 0xbd,
	0xdf, 0xfb, 0xbd, 0x3f, 0xf3, 0xde, 0x18, 0x37, 0x42, 0xb1, 0x07, 0x01, 0x30, 0x97, 0xef, 0x78,
	0x94, 0xf1, 0x7b, 0x40, 0x1d, 0x08, 0x3a, 0x93, 0x40, 0x48, 0x41, 0x2a, 0xea, 0xa7, 0xb1, 0xe9,
	0x32, 0xe9, 0x4d, 0x47, 0x1d, 0x5b, 0xf8, 0x5d, 0x57, 0xb8, 0xa2, 0xab, 0xe0, 0xd1, 0xf4, 0x91,
	0x3a, 0xa9, 0x83, 0xfa, 0x97, 0x7a, 0x35, 0x6a, 0xa3, 0xb1, 0xb0, 0x1f, 0xcf, 0x0f, 0x2f, 0xfb,
	0x20, 0xa9, 0x99, 0x01, 0xeb, 0xff, 0x20, 0xfc, 0xca, 0xee, 0x44, 0xd8, 0xde, 0x50, 0xd2, 0x40,
	0x0e, 0x4f, 0x83, 0x93, 0x6d, 0xbc, 0xb2, 0x6b, 0x0b, 0x2e, 0x7c, 0x66, 0x87, 0x1a, 0x6a, 0xa1,
	0x76, 0x6d, 0xab, 0x9e, 0xba, 0x74, 0x16, 0xb8, 0x79, 0xf3, 0x69, 0x64, 0x94, 0xe2, 0xc8, 0x58,
	0x81, 0x53, 0xc8, 0xca, 0xbc, 0xc8, 0xcf, 0x08, 0xdf, 0xbe, 0x4f, 0x43, 0x79, 0x97, 0x71, 0x3a,
	0x66, 0xdf, 0x81, 0xb3, 0x13, 0x88, 0x30, 0xcc, 0x95, 0xa5, 0xbd, 0xa4, 0x74, 0x8d, 0x53, 0xdd,
	0x45, 0x1a, 0x19, 0xb1, 0x47, 0x25, 0x35, 0x37, 0xe6, 0x61, 0x6e, 0x8f, 0xaf, 0x52, 0xb3, 0xae,
	0x0e, 0xb6, 0x1e, 0x21, 0xac, 0x15, 0x85, 0x20, 0x1b, 0x78, 0x79, 0xe8, 0xd1, 0xc0, 0xe9, 0xf7,
	0x54, 0xb1, 0x37, 0xcc, 0x5a, 0x1c, 0x19, 0xcb, 0x61, 0x0a, 0x59, 0xa7, 0x36, 0x62, 0xe0, 0x8a,
	0x92, 0xd0, 0x56, 0x14, 0x69, 0x25, 0x8e, 0x8c, 0x0a, 0x24, 0x80, 0x95, 0xe2, 0x09, 0xc1, 0x12,
	0x53, 0xee, 0x68, 0xcb, 0x2d, 0xd4, 0x5e, 0x4a, 0x09, 0x41, 0x02, 0x58, 0x29, 0x9e, 0x10, 0xbe,
	0x14, 0xdc, 0x06, 0xed, 0x5a, 0x46, 0xe0, 0x09, 0x60, 0xa5, 0x38, 0xf9, 0x08, 0xe3, 0x34, 0xe1,
	0x7b, 0x34, 0xf4, 0x54, 0x87, 0xae, 0x9b, 0x5a, 0x1c, 0x19, 0xb7, 0xbc, 0x05, 0xfa, 0x81, 0xf0,
	0x99, 0x04, 0x7f, 0x22, 0x0f, 0xac, 0x1c, 0x77, 0xfd, 0xcf, 0x2a, 0xbe, 0x35, 0xbc, 0x64, 0x7a,
	0xc8, 0x87, 0xb8, 0x3a, 0x6f, 0x78, 0x7a, 0x91, 0x37, 0xe6, 0x0d, 0x4f, 0x41, 0x13, 0xc7, 0x91,
	0x51, 0x4d, 0xd5, 0xad, 0x39, 0x91, 0x58, 0x78, 0xed, 0x6b, 0x3a, 0x66, 0x0e, 0x95, 0x22, 0x18,
	0x4a, 0x2a, 0x43, 0x4b, 0x08, 0x99, 0xcb, 0xa8, 0x11, 0x47, 0xc6, 0xda, 0xde, 0xa5, 0x0c, 0xab,
	0xc0, 0x93, 0x00, 0x7e, 0x7d, 0x77, 0x5f, 0x02, 0x77, 0xc0, 0x51, 0xfd, 0xcc, 0x52, 0x87, 0x50,
	0x2b, 0xb7, 0xca, 0xed, 0xeb, 0xe6, 0xbb, 0x71, 0x64, 0xbc, 0x05, 0x45, 0xa4, 0x5c, 0xdd, 0xc5,
	0x4a, 0xe4, 0x7b, 0xac, 0x0d, 0xa6, 0xf2, 0x33, 0xc1, 0xb8, 0xfb, 0x05, 0xe3, 0x4c, 0x0d, 0x7b,
	0x4a, 0x08, 0xb5, 0xa5, 0x56, 0xb9, 0x5d, 0xdb, 0xd2, 0xe7, 0xf5, 0x17, 0xd0, 0xcc, 0x56, 0x1c,
	0x19, 0x4d, 0x31, 0x37, 0x0e, 0x26, 0x10, 0x50, 0xc9, 0x04, 0xcf, 0x87, 0x2f, 0x8c, 0x40, 0x7a,
	0x78, 0xb5, 0x1f, 0xaa, 0x09, 0x1b, 0x3c, 0x4a, 0x47, 0xa5, 0xd2, 0x42, 0xed, 0x6b, 0x66, 0x33,
	0x8e, 0x0c, 0x8d, 0x9d, 0xb1, 0xe4, 0xf4, 0xce, 0xf9, 0x90, 0xdf, 0x11, 0x5e, 0xdb, 0xb6, 0xed,
	0xa9, 0x3f, 0x1d, 0x53, 0x09, 0xce, 0x5d, 0x80, 0xb0, 0xcf, 0x53, 0xb9, 0xaa, 0xea, 0xbf, 0x1f,
	0x47, 0x46, 0x8b, 0x5e, 0xca, 0xc8, 0x64, 0x9f, 0xfc, 0x65, 0xec, 0xfa, 0x54, 0x7a, 0xdd, 0x11,
	0x73, 0x3b, 0x7d, 0x2e, 0x3f, 0xce, 0x3d, 0x1c, 0xfe, 0x74, 0x2c, 0xd9, 0x1e, 0x04, 0xe1, 0x7e,
	0xd7, 0xdf, 0xdf, 0xb4, 0x93, 0x69, 0xd9, 0xb4, 0x45, 0x00, 0x9b, 0xae, 0xe8, 0x3a, 0x54, 0xd2,
	0x8e, 0xc9, 0xdc, 0x3e, 0x97, 0x3b, 0x34, 0x94, 0x10, 0x58, 0x05, 0xc9, 0x90, 0x5f, 0x10, 0x5e,
	0xed, 0xc1, 0x5e, 0x3e, 0xbf, 0x65, 0x95, 0x1f, 0x24, 0xe5, 0x3a, 0x67, 0x2c, 0xff, 0x47, 0x5e,
	0xe7, 0x82, 0x93, 0x6f, 0x30, 0xce, 0x56, 0x5c, 0xad, 0x58, 0x6d, 0xab, 0x71, 0xe1, 0x79, 0x59,
	0x2c, 0x89, 0xd9, 0x9c, 0xbf, 0x2c, 0xb7, 0x60, 0x61, 0xcc, 0x2f, 0x57, 0xe6, 0xb2, 0xfe, 0xa4,
	0x8c, 0x5f, 0x2b, 0xb8, 0x74, 0xf2, 0x0e, 0x5e, 0x52, 0xab, 0x81, 0x54, 0xe9, 0x24, 0x8e, 0x8c,
	0x55, 0xef, 0xec, 0x9a, 0x2a, 0x3b, 0xf9, 0x16, 0xaf, 0x0d, 0x2e, 0x4c, 0x55, 0x6e, 0xa9, 0xde,
	0x4e, 0x2e, 0x55, 0x5c, 0xca, 0xc8, 0x69, 0x15, 0x68, 0x90, 0x9f, 0x10, 0xde, 0xd8, 0x76, 0xdd,
	0x00, 0xdc, 0xe4, 0x96, 0x86, 0xcc, 0xe5, 0x54, 0x4e, 0x03, 0xb8, 0xc8, 0xd6, 0xca, 0x2a, 0xda,
	0x9d, 0x38, 0x32, 0xba, 0xf4, 0x45, 0x1c, 0x72, 0xc1, 0x5f, 0x2c, 0x02, 0xf9, 0x01, 0xbf, 0x79,
	0x5f, 0xf5, 0xe6, 0xaa, 0x34, 0x96, 0x54, 0x1a, 0xdd, 0x38, 0x32, 0xde, 0x1f, 0x3f, 0x8f, 0x9c,
	0x4b, 0xe1, 0xf9, 0xca, 0xef, 0xfd, 0x86, 0xf0, 0x6a, 0x06, 0x3f, 0x38, 0x98, 0x00, 0x79, 0x15,
	0xdf, 0xcc, 0x90, 0x1e, 0x4c, 0x44, 0xc8, 0x64, 0xbd, 0x44, 0x5a, 0xb8, 0x99, 0xc1, 0x3b, 0x1e,
	0xe5, 0x2e, 0x64, 0xaf, 0x17, 0xc8, 0xba, 0x4e, 0xde, 0xc8, 0xee, 0x7d, 0x30, 0xb1, 0xc0, 0x65,
	0xc9, 0xe0, 0x3d, 0x10, 0x8f, 0x81, 0xd7, 0x3f, 0x21, 0xcd, 0xec, 0xad, 0xc9, 0x8c, 0xe6, 0x38,
	0xfc, 0x1c, 0x0e, 0xea, 0x0f, 0x89, 0x8e, 0x1b, 0x99, 0xf5, 0x2b, 0x7e, 0xce, 0xbe, 0x6f, 0x7e,
	0x7a, 0x78, 0xac, 0x97, 0x8e, 0x8e, 0xf5, 0xd2, 0xb3, 0x63, 0x1d, 0xfd, 0x38, 0xd3, 0xd1, 0x1f,
	0x33, 0x1d, 0x3d, 0x9d, 0xe9, 0xe8, 0x70, 0xa6, 0xa3, 0xa3, 0x99, 0x8e, 0xfe, 0x9e, 0xe9, 0xe8,
	0xdf, 0x99, 0x5e, 0x7a, 0x36, 0xd3, 0xd1, 0xaf, 0x27, 0x7a, 0xe9, 0xf0, 0x44, 0x2f, 0x1d, 0x9d,
	0xe8, 0xa5, 0x87, 0x15, 0xf5, 0x4d, 0x1f, 0x55, 0xd5, 0x64, 0xdf, 0xf9, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x41, 0x63, 0xd2, 0x00, 0x35, 0x08, 0x00, 0x00,
}

func (x OutGoingOpType) String() string {
	s, ok := OutGoingOpType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *EpochStartSovereign) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EpochStartSovereign)
	if !ok {
		that2, ok := that.(EpochStartSovereign)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Economics.Equal(&that1.Economics) {
		return false
	}
	if !this.LastFinalizedCrossChainHeader.Equal(&that1.LastFinalizedCrossChainHeader) {
		return false
	}
	return true
}
func (this *EpochStartCrossChainData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EpochStartCrossChainData)
	if !ok {
		that2, ok := that.(EpochStartCrossChainData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ShardID != that1.ShardID {
		return false
	}
	if this.Epoch != that1.Epoch {
		return false
	}
	if this.Round != that1.Round {
		return false
	}
	if this.Nonce != that1.Nonce {
		return false
	}
	if !bytes.Equal(this.HeaderHash, that1.HeaderHash) {
		return false
	}
	return true
}
func (this *SovereignChainHeader) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SovereignChainHeader)
	if !ok {
		that2, ok := that.(SovereignChainHeader)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Header.Equal(that1.Header) {
		return false
	}
	if !bytes.Equal(this.ValidatorStatsRootHash, that1.ValidatorStatsRootHash) {
		return false
	}
	if len(this.ExtendedShardHeaderHashes) != len(that1.ExtendedShardHeaderHashes) {
		return false
	}
	for i := range this.ExtendedShardHeaderHashes {
		if !bytes.Equal(this.ExtendedShardHeaderHashes[i], that1.ExtendedShardHeaderHashes[i]) {
			return false
		}
	}
	if len(this.OutGoingMiniBlockHeaders) != len(that1.OutGoingMiniBlockHeaders) {
		return false
	}
	for i := range this.OutGoingMiniBlockHeaders {
		if !this.OutGoingMiniBlockHeaders[i].Equal(that1.OutGoingMiniBlockHeaders[i]) {
			return false
		}
	}
	if this.IsStartOfEpoch != that1.IsStartOfEpoch {
		return false
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.AccumulatedFeesInEpoch, that1.AccumulatedFeesInEpoch) {
			return false
		}
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.DevFeesInEpoch, that1.DevFeesInEpoch) {
			return false
		}
	}
	if !this.EpochStart.Equal(&that1.EpochStart) {
		return false
	}
	return true
}
func (this *OutGoingMiniBlockHeader) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OutGoingMiniBlockHeader)
	if !ok {
		that2, ok := that.(OutGoingMiniBlockHeader)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Hash, that1.Hash) {
		return false
	}
	if !bytes.Equal(this.OutGoingOperationsHash, that1.OutGoingOperationsHash) {
		return false
	}
	if !bytes.Equal(this.AggregatedSignatureOutGoingOperations, that1.AggregatedSignatureOutGoingOperations) {
		return false
	}
	if !bytes.Equal(this.LeaderSignatureOutGoingOperations, that1.LeaderSignatureOutGoingOperations) {
		return false
	}
	return true
}
func (this *EpochStartSovereign) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&block.EpochStartSovereign{")
	s = append(s, "Economics: "+strings.Replace(this.Economics.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "LastFinalizedCrossChainHeader: "+strings.Replace(this.LastFinalizedCrossChainHeader.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *EpochStartCrossChainData) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&block.EpochStartCrossChainData{")
	s = append(s, "ShardID: "+fmt.Sprintf("%#v", this.ShardID)+",\n")
	s = append(s, "Epoch: "+fmt.Sprintf("%#v", this.Epoch)+",\n")
	s = append(s, "Round: "+fmt.Sprintf("%#v", this.Round)+",\n")
	s = append(s, "Nonce: "+fmt.Sprintf("%#v", this.Nonce)+",\n")
	s = append(s, "HeaderHash: "+fmt.Sprintf("%#v", this.HeaderHash)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SovereignChainHeader) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&block.SovereignChainHeader{")
	if this.Header != nil {
		s = append(s, "Header: "+fmt.Sprintf("%#v", this.Header)+",\n")
	}
	s = append(s, "ValidatorStatsRootHash: "+fmt.Sprintf("%#v", this.ValidatorStatsRootHash)+",\n")
	s = append(s, "ExtendedShardHeaderHashes: "+fmt.Sprintf("%#v", this.ExtendedShardHeaderHashes)+",\n")
	if this.OutGoingMiniBlockHeaders != nil {
		s = append(s, "OutGoingMiniBlockHeaders: "+fmt.Sprintf("%#v", this.OutGoingMiniBlockHeaders)+",\n")
	}
	s = append(s, "IsStartOfEpoch: "+fmt.Sprintf("%#v", this.IsStartOfEpoch)+",\n")
	s = append(s, "AccumulatedFeesInEpoch: "+fmt.Sprintf("%#v", this.AccumulatedFeesInEpoch)+",\n")
	s = append(s, "DevFeesInEpoch: "+fmt.Sprintf("%#v", this.DevFeesInEpoch)+",\n")
	s = append(s, "EpochStart: "+strings.Replace(this.EpochStart.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *OutGoingMiniBlockHeader) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&block.OutGoingMiniBlockHeader{")
	s = append(s, "Hash: "+fmt.Sprintf("%#v", this.Hash)+",\n")
	s = append(s, "OutGoingOperationsHash: "+fmt.Sprintf("%#v", this.OutGoingOperationsHash)+",\n")
	s = append(s, "AggregatedSignatureOutGoingOperations: "+fmt.Sprintf("%#v", this.AggregatedSignatureOutGoingOperations)+",\n")
	s = append(s, "LeaderSignatureOutGoingOperations: "+fmt.Sprintf("%#v", this.LeaderSignatureOutGoingOperations)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSovereignChainHeader(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *EpochStartSovereign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochStartSovereign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochStartSovereign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LastFinalizedCrossChainHeader.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Economics.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EpochStartCrossChainData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochStartCrossChainData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochStartCrossChainData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x48
	}
	if m.Nonce != 0 {
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x40
	}
	if m.Round != 0 {
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x38
	}
	if len(m.HeaderHash) > 0 {
		i -= len(m.HeaderHash)
		copy(dAtA[i:], m.HeaderHash)
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(len(m.HeaderHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.ShardID != 0 {
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(m.ShardID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SovereignChainHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SovereignChainHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SovereignChainHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.EpochStart.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.DevFeesInEpoch)
		i -= size
		if _, err := __caster.MarshalTo(m.DevFeesInEpoch, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.AccumulatedFeesInEpoch)
		i -= size
		if _, err := __caster.MarshalTo(m.AccumulatedFeesInEpoch, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.IsStartOfEpoch {
		i--
		if m.IsStartOfEpoch {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.OutGoingMiniBlockHeaders) > 0 {
		for iNdEx := len(m.OutGoingMiniBlockHeaders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OutGoingMiniBlockHeaders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSovereignChainHeader(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ExtendedShardHeaderHashes) > 0 {
		for iNdEx := len(m.ExtendedShardHeaderHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ExtendedShardHeaderHashes[iNdEx])
			copy(dAtA[i:], m.ExtendedShardHeaderHashes[iNdEx])
			i = encodeVarintSovereignChainHeader(dAtA, i, uint64(len(m.ExtendedShardHeaderHashes[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ValidatorStatsRootHash) > 0 {
		i -= len(m.ValidatorStatsRootHash)
		copy(dAtA[i:], m.ValidatorStatsRootHash)
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(len(m.ValidatorStatsRootHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Header != nil {
		{
			size, err := m.Header.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSovereignChainHeader(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OutGoingMiniBlockHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OutGoingMiniBlockHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OutGoingMiniBlockHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LeaderSignatureOutGoingOperations) > 0 {
		i -= len(m.LeaderSignatureOutGoingOperations)
		copy(dAtA[i:], m.LeaderSignatureOutGoingOperations)
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(len(m.LeaderSignatureOutGoingOperations)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AggregatedSignatureOutGoingOperations) > 0 {
		i -= len(m.AggregatedSignatureOutGoingOperations)
		copy(dAtA[i:], m.AggregatedSignatureOutGoingOperations)
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(len(m.AggregatedSignatureOutGoingOperations)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OutGoingOperationsHash) > 0 {
		i -= len(m.OutGoingOperationsHash)
		copy(dAtA[i:], m.OutGoingOperationsHash)
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(len(m.OutGoingOperationsHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintSovereignChainHeader(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSovereignChainHeader(dAtA []byte, offset int, v uint64) int {
	offset -= sovSovereignChainHeader(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EpochStartSovereign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Economics.Size()
	n += 1 + l + sovSovereignChainHeader(uint64(l))
	l = m.LastFinalizedCrossChainHeader.Size()
	n += 1 + l + sovSovereignChainHeader(uint64(l))
	return n
}

func (m *EpochStartCrossChainData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ShardID != 0 {
		n += 1 + sovSovereignChainHeader(uint64(m.ShardID))
	}
	l = len(m.HeaderHash)
	if l > 0 {
		n += 1 + l + sovSovereignChainHeader(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovSovereignChainHeader(uint64(m.Round))
	}
	if m.Nonce != 0 {
		n += 1 + sovSovereignChainHeader(uint64(m.Nonce))
	}
	if m.Epoch != 0 {
		n += 1 + sovSovereignChainHeader(uint64(m.Epoch))
	}
	return n
}

func (m *SovereignChainHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != nil {
		l = m.Header.Size()
		n += 1 + l + sovSovereignChainHeader(uint64(l))
	}
	l = len(m.ValidatorStatsRootHash)
	if l > 0 {
		n += 1 + l + sovSovereignChainHeader(uint64(l))
	}
	if len(m.ExtendedShardHeaderHashes) > 0 {
		for _, b := range m.ExtendedShardHeaderHashes {
			l = len(b)
			n += 1 + l + sovSovereignChainHeader(uint64(l))
		}
	}
	if len(m.OutGoingMiniBlockHeaders) > 0 {
		for _, e := range m.OutGoingMiniBlockHeaders {
			l = e.Size()
			n += 1 + l + sovSovereignChainHeader(uint64(l))
		}
	}
	if m.IsStartOfEpoch {
		n += 2
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.AccumulatedFeesInEpoch)
		n += 1 + l + sovSovereignChainHeader(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.DevFeesInEpoch)
		n += 1 + l + sovSovereignChainHeader(uint64(l))
	}
	l = m.EpochStart.Size()
	n += 1 + l + sovSovereignChainHeader(uint64(l))
	return n
}

func (m *OutGoingMiniBlockHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovSovereignChainHeader(uint64(l))
	}
	l = len(m.OutGoingOperationsHash)
	if l > 0 {
		n += 1 + l + sovSovereignChainHeader(uint64(l))
	}
	l = len(m.AggregatedSignatureOutGoingOperations)
	if l > 0 {
		n += 1 + l + sovSovereignChainHeader(uint64(l))
	}
	l = len(m.LeaderSignatureOutGoingOperations)
	if l > 0 {
		n += 1 + l + sovSovereignChainHeader(uint64(l))
	}
	return n
}

func sovSovereignChainHeader(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSovereignChainHeader(x uint64) (n int) {
	return sovSovereignChainHeader(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *EpochStartSovereign) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EpochStartSovereign{`,
		`Economics:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Economics), "Economics", "Economics", 1), `&`, ``, 1) + `,`,
		`LastFinalizedCrossChainHeader:` + strings.Replace(strings.Replace(this.LastFinalizedCrossChainHeader.String(), "EpochStartCrossChainData", "EpochStartCrossChainData", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EpochStartCrossChainData) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EpochStartCrossChainData{`,
		`ShardID:` + fmt.Sprintf("%v", this.ShardID) + `,`,
		`HeaderHash:` + fmt.Sprintf("%v", this.HeaderHash) + `,`,
		`Round:` + fmt.Sprintf("%v", this.Round) + `,`,
		`Nonce:` + fmt.Sprintf("%v", this.Nonce) + `,`,
		`Epoch:` + fmt.Sprintf("%v", this.Epoch) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SovereignChainHeader) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForOutGoingMiniBlockHeaders := "[]*OutGoingMiniBlockHeader{"
	for _, f := range this.OutGoingMiniBlockHeaders {
		repeatedStringForOutGoingMiniBlockHeaders += strings.Replace(f.String(), "OutGoingMiniBlockHeader", "OutGoingMiniBlockHeader", 1) + ","
	}
	repeatedStringForOutGoingMiniBlockHeaders += "}"
	s := strings.Join([]string{`&SovereignChainHeader{`,
		`Header:` + strings.Replace(fmt.Sprintf("%v", this.Header), "Header", "Header", 1) + `,`,
		`ValidatorStatsRootHash:` + fmt.Sprintf("%v", this.ValidatorStatsRootHash) + `,`,
		`ExtendedShardHeaderHashes:` + fmt.Sprintf("%v", this.ExtendedShardHeaderHashes) + `,`,
		`OutGoingMiniBlockHeaders:` + repeatedStringForOutGoingMiniBlockHeaders + `,`,
		`IsStartOfEpoch:` + fmt.Sprintf("%v", this.IsStartOfEpoch) + `,`,
		`AccumulatedFeesInEpoch:` + fmt.Sprintf("%v", this.AccumulatedFeesInEpoch) + `,`,
		`DevFeesInEpoch:` + fmt.Sprintf("%v", this.DevFeesInEpoch) + `,`,
		`EpochStart:` + strings.Replace(strings.Replace(this.EpochStart.String(), "EpochStartSovereign", "EpochStartSovereign", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *OutGoingMiniBlockHeader) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&OutGoingMiniBlockHeader{`,
		`Hash:` + fmt.Sprintf("%v", this.Hash) + `,`,
		`OutGoingOperationsHash:` + fmt.Sprintf("%v", this.OutGoingOperationsHash) + `,`,
		`AggregatedSignatureOutGoingOperations:` + fmt.Sprintf("%v", this.AggregatedSignatureOutGoingOperations) + `,`,
		`LeaderSignatureOutGoingOperations:` + fmt.Sprintf("%v", this.LeaderSignatureOutGoingOperations) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringSovereignChainHeader(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *EpochStartSovereign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereignChainHeader
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochStartSovereign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochStartSovereign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Economics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Economics.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastFinalizedCrossChainHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastFinalizedCrossChainHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSovereignChainHeader(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochStartCrossChainData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereignChainHeader
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochStartCrossChainData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochStartCrossChainData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardID", wireType)
			}
			m.ShardID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeaderHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeaderHash = append(m.HeaderHash[:0], dAtA[iNdEx:postIndex]...)
			if m.HeaderHash == nil {
				m.HeaderHash = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSovereignChainHeader(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SovereignChainHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereignChainHeader
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SovereignChainHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SovereignChainHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header == nil {
				m.Header = &Header{}
			}
			if err := m.Header.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorStatsRootHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorStatsRootHash = append(m.ValidatorStatsRootHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorStatsRootHash == nil {
				m.ValidatorStatsRootHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendedShardHeaderHashes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtendedShardHeaderHashes = append(m.ExtendedShardHeaderHashes, make([]byte, postIndex-iNdEx))
			copy(m.ExtendedShardHeaderHashes[len(m.ExtendedShardHeaderHashes)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutGoingMiniBlockHeaders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutGoingMiniBlockHeaders = append(m.OutGoingMiniBlockHeaders, &OutGoingMiniBlockHeader{})
			if err := m.OutGoingMiniBlockHeaders[len(m.OutGoingMiniBlockHeaders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsStartOfEpoch", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsStartOfEpoch = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumulatedFeesInEpoch", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.AccumulatedFeesInEpoch = tmp
				}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DevFeesInEpoch", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.DevFeesInEpoch = tmp
				}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStart", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EpochStart.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSovereignChainHeader(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OutGoingMiniBlockHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSovereignChainHeader
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OutGoingMiniBlockHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OutGoingMiniBlockHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutGoingOperationsHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutGoingOperationsHash = append(m.OutGoingOperationsHash[:0], dAtA[iNdEx:postIndex]...)
			if m.OutGoingOperationsHash == nil {
				m.OutGoingOperationsHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregatedSignatureOutGoingOperations", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AggregatedSignatureOutGoingOperations = append(m.AggregatedSignatureOutGoingOperations[:0], dAtA[iNdEx:postIndex]...)
			if m.AggregatedSignatureOutGoingOperations == nil {
				m.AggregatedSignatureOutGoingOperations = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderSignatureOutGoingOperations", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LeaderSignatureOutGoingOperations = append(m.LeaderSignatureOutGoingOperations[:0], dAtA[iNdEx:postIndex]...)
			if m.LeaderSignatureOutGoingOperations == nil {
				m.LeaderSignatureOutGoingOperations = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSovereignChainHeader(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSovereignChainHeader
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSovereignChainHeader(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSovereignChainHeader
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSovereignChainHeader
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSovereignChainHeader
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSovereignChainHeader
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSovereignChainHeader
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSovereignChainHeader        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSovereignChainHeader          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSovereignChainHeader = fmt.Errorf("proto: unexpected end of group")
)
