// Code generated by protoc-gen-go. DO NOT EDIT.
// source: outGoingBridgeData.proto

package sovereign

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BridgeOperations struct {
	Data                 []*BridgeOutGoingData `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BridgeOperations) Reset()         { *m = BridgeOperations{} }
func (m *BridgeOperations) String() string { return proto.CompactTextString(m) }
func (*BridgeOperations) ProtoMessage()    {}
func (*BridgeOperations) Descriptor() ([]byte, []int) {
	return fileDescriptor_62fb23e431426efc, []int{0}
}

func (m *BridgeOperations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeOperations.Unmarshal(m, b)
}
func (m *BridgeOperations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeOperations.Marshal(b, m, deterministic)
}
func (m *BridgeOperations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeOperations.Merge(m, src)
}
func (m *BridgeOperations) XXX_Size() int {
	return xxx_messageInfo_BridgeOperations.Size(m)
}
func (m *BridgeOperations) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeOperations.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeOperations proto.InternalMessageInfo

func (m *BridgeOperations) GetData() []*BridgeOutGoingData {
	if m != nil {
		return m.Data
	}
	return nil
}

type BridgeOutGoingData struct {
	Type                 int32                `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Hash                 []byte               `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	OutGoingOperations   []*OutGoingOperation `protobuf:"bytes,3,rep,name=OutGoingOperations,proto3" json:"OutGoingOperations,omitempty"`
	AggregatedSignature  []byte               `protobuf:"bytes,4,opt,name=AggregatedSignature,proto3" json:"AggregatedSignature,omitempty"`
	LeaderSignature      []byte               `protobuf:"bytes,5,opt,name=LeaderSignature,proto3" json:"LeaderSignature,omitempty"`
	PubKeysBitmap        []byte               `protobuf:"bytes,6,opt,name=PubKeysBitmap,proto3" json:"PubKeysBitmap,omitempty"`
	Epoch                uint32               `protobuf:"varint,7,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BridgeOutGoingData) Reset()         { *m = BridgeOutGoingData{} }
func (m *BridgeOutGoingData) String() string { return proto.CompactTextString(m) }
func (*BridgeOutGoingData) ProtoMessage()    {}
func (*BridgeOutGoingData) Descriptor() ([]byte, []int) {
	return fileDescriptor_62fb23e431426efc, []int{1}
}

func (m *BridgeOutGoingData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeOutGoingData.Unmarshal(m, b)
}
func (m *BridgeOutGoingData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeOutGoingData.Marshal(b, m, deterministic)
}
func (m *BridgeOutGoingData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeOutGoingData.Merge(m, src)
}
func (m *BridgeOutGoingData) XXX_Size() int {
	return xxx_messageInfo_BridgeOutGoingData.Size(m)
}
func (m *BridgeOutGoingData) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeOutGoingData.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeOutGoingData proto.InternalMessageInfo

func (m *BridgeOutGoingData) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *BridgeOutGoingData) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BridgeOutGoingData) GetOutGoingOperations() []*OutGoingOperation {
	if m != nil {
		return m.OutGoingOperations
	}
	return nil
}

func (m *BridgeOutGoingData) GetAggregatedSignature() []byte {
	if m != nil {
		return m.AggregatedSignature
	}
	return nil
}

func (m *BridgeOutGoingData) GetLeaderSignature() []byte {
	if m != nil {
		return m.LeaderSignature
	}
	return nil
}

func (m *BridgeOutGoingData) GetPubKeysBitmap() []byte {
	if m != nil {
		return m.PubKeysBitmap
	}
	return nil
}

func (m *BridgeOutGoingData) GetEpoch() uint32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

type OutGoingOperation struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutGoingOperation) Reset()         { *m = OutGoingOperation{} }
func (m *OutGoingOperation) String() string { return proto.CompactTextString(m) }
func (*OutGoingOperation) ProtoMessage()    {}
func (*OutGoingOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_62fb23e431426efc, []int{2}
}

func (m *OutGoingOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutGoingOperation.Unmarshal(m, b)
}
func (m *OutGoingOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutGoingOperation.Marshal(b, m, deterministic)
}
func (m *OutGoingOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutGoingOperation.Merge(m, src)
}
func (m *OutGoingOperation) XXX_Size() int {
	return xxx_messageInfo_OutGoingOperation.Size(m)
}
func (m *OutGoingOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_OutGoingOperation.DiscardUnknown(m)
}

var xxx_messageInfo_OutGoingOperation proto.InternalMessageInfo

func (m *OutGoingOperation) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *OutGoingOperation) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BridgeOutGoingDataValidatorSetChange struct {
	PubKeyIDs            [][]byte `protobuf:"bytes,1,rep,name=PubKeyIDs,proto3" json:"PubKeyIDs,omitempty"`
	Epoch                uint32   `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BridgeOutGoingDataValidatorSetChange) Reset()         { *m = BridgeOutGoingDataValidatorSetChange{} }
func (m *BridgeOutGoingDataValidatorSetChange) String() string { return proto.CompactTextString(m) }
func (*BridgeOutGoingDataValidatorSetChange) ProtoMessage()    {}
func (*BridgeOutGoingDataValidatorSetChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_62fb23e431426efc, []int{3}
}

func (m *BridgeOutGoingDataValidatorSetChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeOutGoingDataValidatorSetChange.Unmarshal(m, b)
}
func (m *BridgeOutGoingDataValidatorSetChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeOutGoingDataValidatorSetChange.Marshal(b, m, deterministic)
}
func (m *BridgeOutGoingDataValidatorSetChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeOutGoingDataValidatorSetChange.Merge(m, src)
}
func (m *BridgeOutGoingDataValidatorSetChange) XXX_Size() int {
	return xxx_messageInfo_BridgeOutGoingDataValidatorSetChange.Size(m)
}
func (m *BridgeOutGoingDataValidatorSetChange) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeOutGoingDataValidatorSetChange.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeOutGoingDataValidatorSetChange proto.InternalMessageInfo

func (m *BridgeOutGoingDataValidatorSetChange) GetPubKeyIDs() [][]byte {
	if m != nil {
		return m.PubKeyIDs
	}
	return nil
}

func (m *BridgeOutGoingDataValidatorSetChange) GetEpoch() uint32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

type BridgeOperationsResponse struct {
	TxHashes             []string `protobuf:"bytes,1,rep,name=TxHashes,proto3" json:"TxHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BridgeOperationsResponse) Reset()         { *m = BridgeOperationsResponse{} }
func (m *BridgeOperationsResponse) String() string { return proto.CompactTextString(m) }
func (*BridgeOperationsResponse) ProtoMessage()    {}
func (*BridgeOperationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62fb23e431426efc, []int{4}
}

func (m *BridgeOperationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeOperationsResponse.Unmarshal(m, b)
}
func (m *BridgeOperationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeOperationsResponse.Marshal(b, m, deterministic)
}
func (m *BridgeOperationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeOperationsResponse.Merge(m, src)
}
func (m *BridgeOperationsResponse) XXX_Size() int {
	return xxx_messageInfo_BridgeOperationsResponse.Size(m)
}
func (m *BridgeOperationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeOperationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeOperationsResponse proto.InternalMessageInfo

func (m *BridgeOperationsResponse) GetTxHashes() []string {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*BridgeOperations)(nil), "sovereign.BridgeOperations")
	proto.RegisterType((*BridgeOutGoingData)(nil), "sovereign.BridgeOutGoingData")
	proto.RegisterType((*OutGoingOperation)(nil), "sovereign.OutGoingOperation")
	proto.RegisterType((*BridgeOutGoingDataValidatorSetChange)(nil), "sovereign.BridgeOutGoingDataValidatorSetChange")
	proto.RegisterType((*BridgeOperationsResponse)(nil), "sovereign.BridgeOperationsResponse")
}

func init() {
	proto.RegisterFile("outGoingBridgeData.proto", fileDescriptor_62fb23e431426efc)
}

var fileDescriptor_62fb23e431426efc = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x86, 0x71, 0x9a, 0x14, 0x32, 0xb4, 0x7c, 0x0c, 0x1c, 0x56, 0xa5, 0x48, 0x51, 0xe8, 0xc1,
	0x97, 0x24, 0x50, 0x24, 0x2e, 0x3d, 0xa0, 0x86, 0x56, 0x7c, 0x55, 0x02, 0x6d, 0x22, 0x0e, 0x15,
	0x97, 0x4d, 0x3c, 0x5a, 0xaf, 0xd4, 0xec, 0x5a, 0xbb, 0xeb, 0xca, 0xfd, 0x3b, 0xfc, 0x52, 0xe4,
	0xb5, 0x6b, 0x87, 0xba, 0xe2, 0x36, 0x3b, 0xf3, 0xcc, 0xcc, 0xab, 0x77, 0x07, 0x98, 0xc9, 0xfd,
	0x67, 0xa3, 0xb4, 0x9c, 0x5b, 0x95, 0x48, 0x3a, 0x13, 0x5e, 0x4c, 0x33, 0x6b, 0xbc, 0xc1, 0xa1,
	0x33, 0xd7, 0x64, 0x49, 0x49, 0x3d, 0x3e, 0x87, 0x67, 0x55, 0xf9, 0x47, 0x46, 0x56, 0x78, 0x65,
	0xb4, 0xc3, 0x77, 0xd0, 0x2f, 0x61, 0x16, 0x8d, 0x76, 0xe2, 0xc7, 0xc7, 0xaf, 0xa7, 0x0d, 0x3d,
	0xad, 0xd1, 0x7a, 0x6e, 0x09, 0xf1, 0x80, 0x8e, 0xff, 0xf4, 0x00, 0xbb, 0x45, 0x44, 0xe8, 0x2f,
	0x6f, 0x32, 0x62, 0xd1, 0x28, 0x8a, 0x07, 0x3c, 0xc4, 0x65, 0xee, 0x8b, 0x70, 0x29, 0xeb, 0x8d,
	0xa2, 0x78, 0x8f, 0x87, 0x18, 0x2f, 0x00, 0x6f, 0xfb, 0x5a, 0x1d, 0x6c, 0x27, 0xec, 0x3f, 0xdc,
	0xda, 0xdf, 0x81, 0xf8, 0x3d, 0x7d, 0xf8, 0x16, 0x5e, 0x9c, 0x4a, 0x69, 0x49, 0x0a, 0x4f, 0xc9,
	0x42, 0x49, 0x2d, 0x7c, 0x6e, 0x89, 0xf5, 0xc3, 0xc2, 0xfb, 0x4a, 0x18, 0xc3, 0xd3, 0x0b, 0x12,
	0x09, 0xd9, 0x96, 0x1e, 0x04, 0xfa, 0x6e, 0x1a, 0x8f, 0x60, 0xff, 0x67, 0xbe, 0xfa, 0x4e, 0x37,
	0x6e, 0xae, 0xfc, 0x46, 0x64, 0x6c, 0x37, 0x70, 0xff, 0x26, 0xf1, 0x25, 0x0c, 0xce, 0x33, 0xb3,
	0x4e, 0xd9, 0xc3, 0x51, 0x14, 0xef, 0xf3, 0xea, 0x31, 0x3e, 0x81, 0xe7, 0x1d, 0xb5, 0x8d, 0x1d,
	0xd1, 0x96, 0x1d, 0x58, 0x7f, 0x40, 0x6d, 0x51, 0x70, 0xf8, 0x12, 0x8e, 0xba, 0x06, 0xff, 0x12,
	0x57, 0x2a, 0x11, 0xde, 0xd8, 0x05, 0xf9, 0x4f, 0xa9, 0xd0, 0x92, 0xf0, 0x10, 0x86, 0x95, 0x96,
	0xaf, 0x67, 0x2e, 0xfc, 0xe0, 0x1e, 0x6f, 0x13, 0xad, 0xb0, 0xde, 0xb6, 0xb0, 0x0f, 0xc0, 0xee,
	0x1e, 0x01, 0x27, 0x97, 0x19, 0xed, 0x08, 0x0f, 0xe0, 0xd1, 0xb2, 0x28, 0x55, 0x51, 0x35, 0x6e,
	0xc8, 0x9b, 0xf7, 0xf1, 0x6f, 0x78, 0x52, 0xf5, 0x2d, 0x8b, 0x05, 0xe9, 0x84, 0x2c, 0x7e, 0x83,
	0x7e, 0x19, 0xe1, 0xab, 0xee, 0xd1, 0x34, 0xa3, 0x0f, 0xde, 0xfc, 0xa7, 0x78, 0xbb, 0x77, 0xfc,
	0x60, 0x7e, 0x7a, 0xf9, 0x51, 0x2a, 0x9f, 0xe6, 0xab, 0xe9, 0xda, 0x6c, 0x66, 0x9b, 0xfc, 0xca,
	0xab, 0x6b, 0xb2, 0xae, 0x98, 0x6d, 0x8a, 0xc9, 0x3a, 0x15, 0x4a, 0x4f, 0xd6, 0xc6, 0xd2, 0x44,
	0x9a, 0x59, 0x22, 0xbc, 0x98, 0x35, 0x33, 0x4f, 0x9a, 0x68, 0xb5, 0x1b, 0xee, 0xfd, 0xfd, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x81, 0xf9, 0x02, 0x0b, 0x03, 0x00, 0x00,
}
